### ISSUE TITLE
dont off light in lcz and hcz and office

### ISSUE THREAD

**Issue by danya201272** [RogerFK/pro079#2]
I write .079 ultimate 1 and .079 gen 6 and dont off light in lcz and hcz and office

**Comment by RogerFK** [comment]
The entrance zone can't get shut down (the game doesn't let plugins do it), but the HCZ is the only one that gets shut down because I didn't think no-one would reach tier 4/fake their death before the decontamination sequence ends. Will be fixed for the next release, thanks for reporting this!
_Protip: if you want to shut-down the lights without being 079, you can use the Blackout plugin_

**Comment by RogerFK** [comment]
Fixed in the next version https://github.com/RogerFK/pro079/commit/ace3747ff56709691b0493437d7ddc0413d288a4
